[platformio]
default_envs = cyd-ILI9341, cyd-ST7789

[cyd_base]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.psram = enabled
board_build.partitions = huge_app.csv
upload_speed = 921600
lib_deps =
  bblanchon/ArduinoJson
  arduino-libraries/ArduinoHttpClient
  https://github.com/tzapu/WiFiManager.git
  https://github.com/lovyan03/LovyanGFX.git
  lvgl/lvgl@^9.5.0
build_flags =
  -D LGFX_USE_V1
  -D USER_SETUP_LOADED=1
  -D LV_CONF_INCLUDE_SIMPLE
  -I include
  -Os

[env:cyd-ILI9341]
extends = cyd_base
build_flags =
  ${cyd_base.build_flags}
  -D CYD_PANEL_ILI9341

[env:cyd-ST7789]
extends = cyd_base
build_flags =
  ${cyd_base.build_flags}
  -D CYD_PANEL_ST7789